# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginform.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("#topPanel { background-color: qlineargradient(spread:reflect, x1:0.5, y1:0, x2:0, y2:0, stop:0 rgba(91, 204, 233, 100), stop:1 rgba(32, 80, 96, 100));}\n"
"\n"
"\n"
"#signup{color: qradialgradient(spread:repeat, cx:0.5, cy:0.5, radius:0.077, fx:0.5, fy:0.5, stop:0 rgba(0, 169, 255, 147), stop:0.497326 rgba(0, 0, 0, 147), stop:1 rgba(0, 169, 255, 147));}\n"
"\n"
"#warning{color:red;}\n"
"#centralwidget { background-image: url(images/bc4.jpg); }\n"
"\n"
"#loginForm\n"
"{\n"
"  background: rgba(0, 0, 0, 80);\n"
"  border-radius: 8px;\n"
"}\n"
"QLabel { color: white; }\n"
"QLineEdit { border-radius: 3px; }\n"
"QPushButton\n"
"{\n"
"  color: white;\n"
"  background-color: #27a9e3;\n"
"  border-width: 0px;\n"
"  border-radius: 3px;\n"
"}\n"
"QPushButton:hover{background-color:lightblue;}\n"
"#chatbot{color: qradialgradient(spread:repeat, cx:0.5, cy:0.5, radius:0.077, fx:0.5, fy:0.5, stop:0 rgba(0, 169, 255, 147), stop:0.497326 rgba(0, 0, 0, 147), stop:1 rgba(0, 169, 255, 147));}\n"
"#info{color:red;}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.downPanel = QtWidgets.QWidget(self.centralwidget)
        self.downPanel.setGeometry(QtCore.QRect(0, 100, 800, 481))
        self.downPanel.setObjectName("downPanel")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.downPanel)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 190, 801, 251))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.loginForm = QtWidgets.QWidget(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loginForm.sizePolicy().hasHeightForWidth())
        self.loginForm.setSizePolicy(sizePolicy)
        self.loginForm.setMinimumSize(QtCore.QSize(350, 200))
        self.loginForm.setObjectName("loginForm")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.loginForm)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(30, 30, 301, 31))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(36, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.username = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.username.setMinimumSize(QtCore.QSize(0, 0))
        self.username.setClearButtonEnabled(True)
        self.username.setObjectName("username")
        self.horizontalLayout_3.addWidget(self.username)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.loginForm)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(30, 70, 301, 31))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        spacerItem1 = QtWidgets.QSpacerItem(37, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.password = QtWidgets.QLineEdit(self.horizontalLayoutWidget_4)
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setClearButtonEnabled(True)
        self.password.setObjectName("password")
        self.horizontalLayout_4.addWidget(self.password)
        self.Register = QtWidgets.QPushButton(self.loginForm)
        self.Register.setGeometry(QtCore.QRect(30, 140, 301, 31))
        self.Register.setCheckable(False)
        self.Register.setAutoDefault(False)
        self.Register.setFlat(False)
        self.Register.setObjectName("Register")
        self.Register_2 = QtWidgets.QPushButton(self.loginForm)
        self.Register_2.setGeometry(QtCore.QRect(30, 200, 301, 31))
        self.Register_2.setCheckable(False)
        self.Register_2.setAutoDefault(False)
        self.Register_2.setFlat(False)
        self.Register_2.setObjectName("Register_2")
        self.label_3 = QtWidgets.QLabel(self.loginForm)
        self.label_3.setGeometry(QtCore.QRect(146, 170, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.warning = QtWidgets.QLabel(self.loginForm)
        self.warning.setGeometry(QtCore.QRect(30, 110, 301, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.warning.setFont(font)
        self.warning.setText("")
        self.warning.setAlignment(QtCore.Qt.AlignCenter)
        self.warning.setWordWrap(True)
        self.warning.setObjectName("warning")
        self.horizontalLayout_2.addWidget(self.loginForm)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.downPanel)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 801, 171))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.logo = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logo.sizePolicy().hasHeightForWidth())
        self.logo.setSizePolicy(sizePolicy)
        self.logo.setMinimumSize(QtCore.QSize(150, 150))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.logo.setFont(font)
        self.logo.setStyleSheet("")
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("images/cc.png"))
        self.logo.setObjectName("logo")
        self.horizontalLayout.addWidget(self.logo)
        self.topPanel = QtWidgets.QWidget(self.centralwidget)
        self.topPanel.setGeometry(QtCore.QRect(0, 0, 801, 101))
        self.topPanel.setObjectName("topPanel")
        self.label_5 = QtWidgets.QLabel(self.topPanel)
        self.label_5.setGeometry(QtCore.QRect(0, 10, 801, 91))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setScaledContents(True)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Login"))
        self.label.setText(_translate("MainWindow", "Username:"))
        self.label_2.setText(_translate("MainWindow", "Password:"))
        self.Register.setText(_translate("MainWindow", "Login"))
        self.Register_2.setText(_translate("MainWindow", "Register"))
        self.label_3.setText(_translate("MainWindow", "OR"))
        self.label_5.setText(_translate("MainWindow", "Disease Prognostication & Prevention System"))
